'===================================================================================
' Microsoft patterns & practices
' Composite Application Guidance for Windows Presentation Foundation and Silverlight
'===================================================================================
' Copyright (c) Microsoft Corporation.  All rights reserved.
' THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY
' OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT
' LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
' FITNESS FOR A PARTICULAR PURPOSE.
'===================================================================================
' The example companies, organizations, products, domain names,
' e-mail addresses, logos, people, places, and events depicted
' herein are fictitious.  No association with any real company,
' organization, product, domain name, email address, logo, person,
' places, or events is intended or should be inferred.
'===================================================================================
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System

Namespace StockTraderRI.Tests.AcceptanceTest.TestData


    ''' <summary>
    '''   A strongly-typed resource class, for looking up localized strings, etc.
    ''' </summary>
    ' This class was auto-generated by the StronglyTypedResourceBuilder
    ' class via a tool like ResGen or Visual Studio.
    ' To add or remove a member, edit your .ResX file then rerun ResGen
    ' with the /str option, or rebuild your VS project.
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()> _
    Friend Class ControlIdentifiers

        Private Shared resourceMan As Global.System.Resources.ResourceManager

        Private Shared resourceCulture As Global.System.Globalization.CultureInfo

        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")> _
        Friend Sub New()
        End Sub

        ''' <summary>
        '''   Returns the cached ResourceManager instance used by this class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As New Global.System.Resources.ResourceManager("ControlIdentifiers", GetType(ControlIdentifiers).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property

        ''' <summary>
        '''   Overrides the current thread's CurrentUICulture property for all
        '''   resource lookups using this strongly typed resource class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set(ByVal value As System.Globalization.CultureInfo)
                resourceCulture = value
            End Set
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to ActionsBuyButton.
        ''' </summary>
        Friend Shared ReadOnly Property ActionsBuyButton_Silverlight() As String
            Get
                Return ResourceManager.GetString("ActionsBuyButton_Silverlight", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to ActionsBuyButton.
        ''' </summary>
        Friend Shared ReadOnly Property ActionsBuyButton_Wpf() As String
            Get
                Return ResourceManager.GetString("ActionsBuyButton_Wpf", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to ActionsRemoveButton.
        ''' </summary>
        Friend Shared ReadOnly Property ActionsRemoveButton_Silverlight() As String
            Get
                Return ResourceManager.GetString("ActionsRemoveButton_Silverlight", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to ActionsRemoveButton.
        ''' </summary>
        Friend Shared ReadOnly Property ActionsRemoveButton_Wpf() As String
            Get
                Return ResourceManager.GetString("ActionsRemoveButton_Wpf", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to ActionsSellButton.
        ''' </summary>
        Friend Shared ReadOnly Property ActionsSellButton_Silverlight() As String
            Get
                Return ResourceManager.GetString("ActionsSellButton_Silverlight", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to ActionsSellButton.
        ''' </summary>
        Friend Shared ReadOnly Property ActionsSellButton_Wpf() As String
            Get
                Return ResourceManager.GetString("ActionsSellButton_Wpf", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to AddToWatchListButton.
        ''' </summary>
        Friend Shared ReadOnly Property AddToWatchListButton_Silverlight() As String
            Get
                Return ResourceManager.GetString("AddToWatchListButton_Silverlight", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to AddToWatchListButton.
        ''' </summary>
        Friend Shared ReadOnly Property AddToWatchListButton_Wpf() As String
            Get
                Return ResourceManager.GetString("AddToWatchListButton_Wpf", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to BuyRadioButton.
        ''' </summary>
        Friend Shared ReadOnly Property BuyRadioButton_Silverlight() As String
            Get
                Return ResourceManager.GetString("BuyRadioButton_Silverlight", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to BuyRadioButton.
        ''' </summary>
        Friend Shared ReadOnly Property BuyRadioButton_Wpf() As String
            Get
                Return ResourceManager.GetString("BuyRadioButton_Wpf", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Cancel.
        ''' </summary>
        Friend Shared ReadOnly Property Cancel_Silverlight() As String
            Get
                Return ResourceManager.GetString("Cancel_Silverlight", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Cancel.
        ''' </summary>
        Friend Shared ReadOnly Property Cancel_Wpf() As String
            Get
                Return ResourceManager.GetString("Cancel_Wpf", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Cancel All.
        ''' </summary>
        Friend Shared ReadOnly Property CancelAll_Silverlight() As String
            Get
                Return ResourceManager.GetString("CancelAll_Silverlight", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Cancel All.
        ''' </summary>
        Friend Shared ReadOnly Property CancelAll_Wpf() As String
            Get
                Return ResourceManager.GetString("CancelAll_Wpf", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to CancelAllButton.
        ''' </summary>
        Friend Shared ReadOnly Property CancelAllButton_Silverlight() As String
            Get
                Return ResourceManager.GetString("CancelAllButton_Silverlight", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to CancelAllButton.
        ''' </summary>
        Friend Shared ReadOnly Property CancelAllButton_Wpf() As String
            Get
                Return ResourceManager.GetString("CancelAllButton_Wpf", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to CancelButton.
        ''' </summary>
        Friend Shared ReadOnly Property CancelButton_Silverlight() As String
            Get
                Return ResourceManager.GetString("CancelButton_Silverlight", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to CancelButton.
        ''' </summary>
        Friend Shared ReadOnly Property CancelButton_Wpf() As String
            Get
                Return ResourceManager.GetString("CancelButton_Wpf", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to ExpanderButton.
        ''' </summary>
        Friend Shared ReadOnly Property ExpanderButton_Silverlight() As String
            Get
                Return ResourceManager.GetString("ExpanderButton_Silverlight", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to HistoricalDataChart.
        ''' </summary>
        Friend Shared ReadOnly Property HistoricalDataChart_Silverlight() As String
            Get
                Return ResourceManager.GetString("HistoricalDataChart_Silverlight", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to HistoricalDataChart.
        ''' </summary>
        Friend Shared ReadOnly Property HistoricalDataChart_Wpf() As String
            Get
                Return ResourceManager.GetString("HistoricalDataChart_Wpf", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to HistoricalDataTextBlock.
        ''' </summary>
        Friend Shared ReadOnly Property HistoricalDataTextBlock_Silverlight() As String
            Get
                Return ResourceManager.GetString("HistoricalDataTextBlock_Silverlight", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to HistoricalDataTextBlock.
        ''' </summary>
        Friend Shared ReadOnly Property HistoricalDataTextBlock_Wpf() As String
            Get
                Return ResourceManager.GetString("HistoricalDataTextBlock_Wpf", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to NewsArticleText.
        ''' </summary>
        Friend Shared ReadOnly Property NewsArticleText_Silverlight() As String
            Get
                Return ResourceManager.GetString("NewsArticleText_Silverlight", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to NewsArticleText.
        ''' </summary>
        Friend Shared ReadOnly Property NewsArticleText_Wpf() As String
            Get
                Return ResourceManager.GetString("NewsArticleText_Wpf", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to OrderClickCancel.
        ''' </summary>
        Friend Shared ReadOnly Property OrderCommandCancel_Silverlight() As String
            Get
                Return ResourceManager.GetString("OrderCommandCancel_Silverlight", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to OrderClickCancel.
        ''' </summary>
        Friend Shared ReadOnly Property OrderCommandCancel_Wpf() As String
            Get
                Return ResourceManager.GetString("OrderCommandCancel_Wpf", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to OrderClickCancelAllButton.
        ''' </summary>
        Friend Shared ReadOnly Property OrderCommandCancelAllButton_Silverlight() As String
            Get
                Return ResourceManager.GetString("OrderCommandCancelAllButton_Silverlight", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to OrderClickCancelAllButton.
        ''' </summary>
        Friend Shared ReadOnly Property OrderCommandCancelAllButton_Wpf() As String
            Get
                Return ResourceManager.GetString("OrderCommandCancelAllButton_Wpf", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to OrderClickSubmit.
        ''' </summary>
        Friend Shared ReadOnly Property OrderCommandSubmit_Silverlight() As String
            Get
                Return ResourceManager.GetString("OrderCommandSubmit_Silverlight", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to OrderClickSubmit.
        ''' </summary>
        Friend Shared ReadOnly Property OrderCommandSubmit_Wpf() As String
            Get
                Return ResourceManager.GetString("OrderCommandSubmit_Wpf", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to OrderClickSubmitAllButton.
        ''' </summary>
        Friend Shared ReadOnly Property OrderCommandSubmitAllButton_Silverlight() As String
            Get
                Return ResourceManager.GetString("OrderCommandSubmitAllButton_Silverlight", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to OrderClickSubmitAllButton.
        ''' </summary>
        Friend Shared ReadOnly Property OrderCommandSubmitAllButton_Wpf() As String
            Get
                Return ResourceManager.GetString("OrderCommandSubmitAllButton_Wpf", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to OrderTypeComboBox.
        ''' </summary>
        Friend Shared ReadOnly Property OrderTypeComboBox_Silverlight() As String
            Get
                Return ResourceManager.GetString("OrderTypeComboBox_Silverlight", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to OrderTypeComboBox.
        ''' </summary>
        Friend Shared ReadOnly Property OrderTypeComboBox_Wpf() As String
            Get
                Return ResourceManager.GetString("OrderTypeComboBox_Wpf", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to PieChartTextBlock.
        ''' </summary>
        Friend Shared ReadOnly Property PieChartTextBlock_Silverlight() As String
            Get
                Return ResourceManager.GetString("PieChartTextBlock_Silverlight", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to PieChartTextBlock.
        ''' </summary>
        Friend Shared ReadOnly Property PieChartTextBlock_Wpf() As String
            Get
                Return ResourceManager.GetString("PieChartTextBlock_Wpf", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to PositionBuySellTab.
        ''' </summary>
        Friend Shared ReadOnly Property PositionBuySellTab_Silverlight() As String
            Get
                Return ResourceManager.GetString("PositionBuySellTab_Silverlight", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to PositionBuySellTab.
        ''' </summary>
        Friend Shared ReadOnly Property PositionBuySellTab_Wpf() As String
            Get
                Return ResourceManager.GetString("PositionBuySellTab_Wpf", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to PositionSummaryGrid.
        ''' </summary>
        Friend Shared ReadOnly Property PositionSummaryGrid_Silverlight() As String
            Get
                Return ResourceManager.GetString("PositionSummaryGrid_Silverlight", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to PositionSummaryGrid.
        ''' </summary>
        Friend Shared ReadOnly Property PositionSummaryGrid_Wpf() As String
            Get
                Return ResourceManager.GetString("PositionSummaryGrid_Wpf", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to PositionSummaryTab.
        ''' </summary>
        Friend Shared ReadOnly Property PositionSummaryTab_Silverlight() As String
            Get
                Return ResourceManager.GetString("PositionSummaryTab_Silverlight", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to PositionSummaryTab.
        ''' </summary>
        Friend Shared ReadOnly Property PositionSummaryTab_Wpf() As String
            Get
                Return ResourceManager.GetString("PositionSummaryTab_Wpf", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to PriceLimitTextBox.
        ''' </summary>
        Friend Shared ReadOnly Property PriceLimitTextBox_Silverlight() As String
            Get
                Return ResourceManager.GetString("PriceLimitTextBox_Silverlight", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to PriceLimitTextBox.
        ''' </summary>
        Friend Shared ReadOnly Property PriceLimitTextBox_Wpf() As String
            Get
                Return ResourceManager.GetString("PriceLimitTextBox_Wpf", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to SellRadioButton.
        ''' </summary>
        Friend Shared ReadOnly Property SellRadioButton_Silverlight() As String
            Get
                Return ResourceManager.GetString("SellRadioButton_Silverlight", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to SellRadioButton.
        ''' </summary>
        Friend Shared ReadOnly Property SellRadioButton_Wpf() As String
            Get
                Return ResourceManager.GetString("SellRadioButton_Wpf", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to SharesTextBox.
        ''' </summary>
        Friend Shared ReadOnly Property SharesTextBox_Silverlight() As String
            Get
                Return ResourceManager.GetString("SharesTextBox_Silverlight", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to SharesTextBox.
        ''' </summary>
        Friend Shared ReadOnly Property SharesTextBox_Wpf() As String
            Get
                Return ResourceManager.GetString("SharesTextBox_Wpf", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to StockTraderRI.
        ''' </summary>
        Friend Shared ReadOnly Property SilverlightAppTitle() As String
            Get
                Return ResourceManager.GetString("SilverlightAppTitle", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Submit.
        ''' </summary>
        Friend Shared ReadOnly Property Submit_Silverlight() As String
            Get
                Return ResourceManager.GetString("Submit_Silverlight", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Submit.
        ''' </summary>
        Friend Shared ReadOnly Property Submit_Wpf() As String
            Get
                Return ResourceManager.GetString("Submit_Wpf", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Submit All.
        ''' </summary>
        Friend Shared ReadOnly Property SubmitAll_Silverlight() As String
            Get
                Return ResourceManager.GetString("SubmitAll_Silverlight", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Submit All.
        ''' </summary>
        Friend Shared ReadOnly Property SubmitAll_Wpf() As String
            Get
                Return ResourceManager.GetString("SubmitAll_Wpf", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to SubmitAllButton.
        ''' </summary>
        Friend Shared ReadOnly Property SubmitAllButton_Silverlight() As String
            Get
                Return ResourceManager.GetString("SubmitAllButton_Silverlight", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to SubmitAllButton.
        ''' </summary>
        Friend Shared ReadOnly Property SubmitAllButton_Wpf() As String
            Get
                Return ResourceManager.GetString("SubmitAllButton_Wpf", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to SubmitButton.
        ''' </summary>
        Friend Shared ReadOnly Property SubmitButton_Silverlight() As String
            Get
                Return ResourceManager.GetString("SubmitButton_Silverlight", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to SubmitButton.
        ''' </summary>
        Friend Shared ReadOnly Property SubmitButton_Wpf() As String
            Get
                Return ResourceManager.GetString("SubmitButton_Wpf", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to SymbolTextBox.
        ''' </summary>
        Friend Shared ReadOnly Property SymbolTextBox_Silverlight() As String
            Get
                Return ResourceManager.GetString("SymbolTextBox_Silverlight", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to SymbolTextBox.
        ''' </summary>
        Friend Shared ReadOnly Property SymbolTextBox_Wpf() As String
            Get
                Return ResourceManager.GetString("SymbolTextBox_Wpf", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to TermComboBox.
        ''' </summary>
        Friend Shared ReadOnly Property TermComboBox_Silverlight() As String
            Get
                Return ResourceManager.GetString("TermComboBox_Silverlight", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to TermComboBox.
        ''' </summary>
        Friend Shared ReadOnly Property TermComboBox_Wpf() As String
            Get
                Return ResourceManager.GetString("TermComboBox_Wpf", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to TextBoxBlock.
        ''' </summary>
        Friend Shared ReadOnly Property TextBoxBlock_Silverlight() As String
            Get
                Return ResourceManager.GetString("TextBoxBlock_Silverlight", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to TextBoxBlock.
        ''' </summary>
        Friend Shared ReadOnly Property TextBoxBlock_Wpf() As String
            Get
                Return ResourceManager.GetString("TextBoxBlock_Wpf", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to WatchListGrid.
        ''' </summary>
        Friend Shared ReadOnly Property WatchListGrid_Silverlight() As String
            Get
                Return ResourceManager.GetString("WatchListGrid_Silverlight", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to WatchListGrid.
        ''' </summary>
        Friend Shared ReadOnly Property WatchListGrid_Wpf() As String
            Get
                Return ResourceManager.GetString("WatchListGrid_Wpf", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
