'===================================================================================
' Microsoft patterns & practices
' Composite Application Guidance for Windows Presentation Foundation and Silverlight
'===================================================================================
' Copyright (c) Microsoft Corporation.  All rights reserved.
' THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY
' OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT
' LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
' FITNESS FOR A PARTICULAR PURPOSE.
'===================================================================================
' The example companies, organizations, products, domain names,
' e-mail addresses, logos, people, places, and events depicted
' herein are fictitious.  No association with any real company,
' organization, product, domain name, email address, logo, person,
' places, or events is intended or should be inferred.
'===================================================================================
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System

Namespace My.Resources


   
    ' This class was auto-generated by the StronglyTypedResourceBuilder
    ' class via a tool like ResGen or Visual Studio.
    ' To add or remove a member, edit your .ResX file then rerun ResGen
    ' with the /str option, or rebuild your VS project.
    ''' <summary>
    '''   A strongly-typed resource class, for looking up localized strings, etc.
    ''' </summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(), _
    Global.Microsoft.VisualBasic.HideModuleNameAttribute()> _
    Friend Module Resources

        Private resourceMan As Global.System.Resources.ResourceManager

        Private resourceCulture As Global.System.Globalization.CultureInfo

'        internal Resources()
'        {
'        }

        ''' <summary>
        '''   Returns the cached ResourceManager instance used by this class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As New Global.System.Resources.ResourceManager("Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property

        ''' <summary>
        '''   Overrides the current thread's CurrentUICulture property for all
        '''   resource lookups using this strongly typed resource class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set(ByVal value As System.Globalization.CultureInfo)
                resourceCulture = value
            End Set
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Cannot convert from type {0} to enum type {1}.  The source value must be a string type..
        ''' </summary>
        Friend ReadOnly Property CannotConvertFromTypeToEnum() As String
            Get
                Return ResourceManager.GetString("CannotConvertFromTypeToEnum", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to The parameter should be convertible to an integer..
        ''' </summary>
        Friend ReadOnly Property CannotConvertParameterToIntegerException() As String
            Get
                Return ResourceManager.GetString("CannotConvertParameterToIntegerException", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Behavior cannot be attached to a null Region..
        ''' </summary>
        Friend ReadOnly Property InvalidAttachedRegion() As String
            Get
                Return ResourceManager.GetString("InvalidAttachedRegion", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Cannot apply ActivateViewOnFocusBehavior to a Region that contains Views that are not UIElement..
        ''' </summary>
        Friend ReadOnly Property InvalidViewOnActivateViewOnFocusBehavior() As String
            Get
                Return ResourceManager.GetString("InvalidViewOnActivateViewOnFocusBehavior", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to The type {0} does not have a public property named &apos;{1}&apos;. The current implementation of &apos;{2}&apos; does not allow specifying a nested path or a member that is not a property..
        ''' </summary>
        Friend ReadOnly Property SelectorExtensionCannotResolveMember() As String
            Get
                Return ResourceManager.GetString("SelectorExtensionCannotResolveMember", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
