'===================================================================================
' Microsoft patterns & practices
' Composite Application Guidance for Windows Presentation Foundation and Silverlight
'===================================================================================
' Copyright (c) Microsoft Corporation.  All rights reserved.
' THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY
' OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT
' LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
' FITNESS FOR A PARTICULAR PURPOSE.
'===================================================================================
' The example companies, organizations, products, domain names,
' e-mail addresses, logos, people, places, and events depicted
' herein are fictitious.  No association with any real company,
' organization, product, domain name, email address, logo, person,
' places, or events is intended or should be inferred.
'===================================================================================
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System

Namespace My.Resources


    ''' <summary>
    '''   A strongly-typed resource class, for looking up localized strings, etc.
    ''' </summary>
    ' This class was auto-generated by the StronglyTypedResourceBuilder
    ' class via a tool like ResGen or Visual Studio.
    ' To add or remove a member, edit your .ResX file then rerun ResGen
    ' with the /str option, or rebuild your VS project.
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(), _
    Global.Microsoft.VisualBasic.HideModuleNameAttribute()> _
    Friend Module Resources

        Private resourceMan As Global.System.Resources.ResourceManager

        Private resourceCulture As Global.System.Globalization.CultureInfo

'        internal Resources()
'        {
'        }

        ''' <summary>
        '''   Returns the cached ResourceManager instance used by this class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As New Global.System.Resources.ResourceManager("Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property

        ''' <summary>
        '''   Overrides the current thread's CurrentUICulture property for all
        '''   resource lookups using this strongly typed resource class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set(ByVal value As System.Globalization.CultureInfo)
                resourceCulture = value
            End Set
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ArrayOfAccountPosition xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        '''  &lt;AccountPosition&gt;
        '''    &lt;TickerSymbol&gt;STOCK0&lt;/TickerSymbol&gt;
        '''    &lt;CostBasis&gt;280.99&lt;/CostBasis&gt;
        '''    &lt;Shares&gt;10&lt;/Shares&gt;
        '''  &lt;/AccountPosition&gt;
        '''  &lt;AccountPosition&gt;
        '''    &lt;TickerSymbol&gt;STOCK2&lt;/TickerSymbol&gt;
        '''    &lt;CostBasis&gt;1900.22&lt;/CostBasis&gt;
        '''    &lt;Shares&gt;100&lt;/Shares&gt;
        '''  &lt;/AccountPosition&gt;
        '''  &lt;AccountPosition&gt;
        '''    &lt;TickerSymbol&gt;STOCK3&lt;/TickerSymb [rest of string was truncated]&quot;;.
        ''' </summary>
        Friend ReadOnly Property AccountPositions() As String
            Get
                Return ResourceManager.GetString("AccountPositions", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Shares must be greater than 0.
        ''' </summary>
        Friend ReadOnly Property InvalidSharesRange() As String
            Get
                Return ResourceManager.GetString("InvalidSharesRange", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to The stop limit price must be greater than 0.
        ''' </summary>
        Friend ReadOnly Property InvalidStopLimitPrice() As String
            Get
                Return ResourceManager.GetString("InvalidStopLimitPrice", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to An order has been submitted.
        '''Order Details: {0}.
        ''' </summary>
        Friend ReadOnly Property LogOrderSubmitted() As String
            Get
                Return ResourceManager.GetString("LogOrderSubmitted", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to You don&apos;t have {0} shares to sell.
        ''' </summary>
        Friend ReadOnly Property NotEnoughSharesToSell() As String
            Get
                Return ResourceManager.GetString("NotEnoughSharesToSell", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Limit.
        ''' </summary>
        Friend ReadOnly Property OrderType_Limit() As String
            Get
                Return ResourceManager.GetString("OrderType_Limit", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Market.
        ''' </summary>
        Friend ReadOnly Property OrderType_Market() As String
            Get
                Return ResourceManager.GetString("OrderType_Market", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Stop.
        ''' </summary>
        Friend ReadOnly Property OrderType_Stop() As String
            Get
                Return ResourceManager.GetString("OrderType_Stop", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to The provided String argument {0} must not be null or empty..
        ''' </summary>
        Friend ReadOnly Property StringCannotBeNullOrEmpty() As String
            Get
                Return ResourceManager.GetString("StringCannotBeNullOrEmpty", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to End of day.
        ''' </summary>
        Friend ReadOnly Property TimeInForce_EndOfDay() As String
            Get
                Return ResourceManager.GetString("TimeInForce_EndOfDay", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Thirty days.
        ''' </summary>
        Friend ReadOnly Property TimeInForce_ThirtyDays() As String
            Get
                Return ResourceManager.GetString("TimeInForce_ThirtyDays", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
